#!/bin/bash
echo "=================================================="
echo "   _  ______  ___  __________________";
echo "  / |/ / __ \/ _ \/ __/  _/ __/_  __/";
echo " /    / /_/ / // / _/_/ /_\ \  / /   ";
echo "/_/|_/\____/____/___/___/___/ /_/    ";
echo -e "\e[0m"
echo "==================================================" 

sleep 2


echo "=================================================="

echo -e "\e[1m\e[32m1. NODECORD GO YÜKLENİYOR... \e[0m" && sleep 1
cd $HOME
wget https://golang.org/dl/go1.18.2.linux-amd64.tar.gz
sudo rm -rf /usr/local/go
sudo tar -C /usr/local -xzf go1.18.2.linux-amd64.tar.gz
rm "go1.18.2.linux-amd64.tar.gz"
go version
# GO YAPILANDIRMA
cat <<EOF >> ~/.profile
export GOROOT=/usr/local/go
export GOPATH=$HOME/go
export GO111MODULE=on
export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin
EOF
source ~/.profile
go version

sleep 1

echo "=================================================="

echo -e "\e[1m\e[32m2. NODECORD REPOSU INDIRILIYOR ... \e[0m" && sleep 1
git clone https://github.com/strangelove-ventures/half-life.git
cd ~/half-life
go install

echo "=================================================="

echo -e "\e[1m\e[32m KURULUM BAŞARIYLA TAMAMLANDI... \e[0m" && sleep 1
